name: GriefProtect
version: 1.0
main: ru.anarchy.griefprotect.GriefProtect
api-version: 1.16
depend: [WorldGuard, DecentHolograms]
author: AnarchyDeveloper
commands:
  gprotect:
    description: Главная команда плагина приватов
    permission: griefprotect.admin